let person =  {
        fullName: null,
        age: null,
        gender: null,
        childrenNumber: null,
        married: false,
        childrenAges: [],
        childrenBirthYears: null,
        radioStations: null,
        favouriteRadioShow: null,
        filmGenre: null,
        favouriteFilm: null,
        birthYear: null,
        inPrimarySchool: false,
        satElevenPlus: false,
        passedElevenPlus: false,
        primarySchoolStart: null,
        secondarySchoolStart: null,
        secondarySchoolType: null,
        inWork: false,
        job: null,
        readsDailyNewspaper: false,
        newspaperRead: null,
        money: null,
        fathersJob: null,
        mothersJob: null,
        spousesGender: null,
        spousesJob: null,
        movedHouseYear: null,
        inventory: [],
        familySize: 1,
        classStatus: Math.floor(Math.random() * 10) < 9 ? "Working Class":"Middle Class",
    };